### ISSUE TITLE
Allow users to specify the remote to push tags

### ISSUE THREAD

**Issue by karmann-dm** [karmann-dm/gradle-versions-plugin#3]
Allow users to specify the remote as an argument in `assignTag` task to push new commits and tags

Current outcome:
```
$ ./gradlew assignTag
--> pushed to origin
```

Expected outcome:
```
$ ./gradlew assignTag --remote=github
--> pushed to github
```

**Comment by Szer** [comment]
Oh, haven't seen this issue :) I've created another one, where one of the requested fields is also `remote`
https://github.com/karmann-dm/gradle-versions-plugin/issues/7

**Comment by karmann-dm** [comment]
@Szer Yes, noticed that you've created a couple of issues :D 

Thank you for the attention to the project! 

Unfortunately some features are not implemented yet as far as this was kind of pet project for personal usage, but I'm gonna fix it soon cause I also faced with some problems when using it on my projects.

**Comment by karmann-dm** [comment]
Closed, mainly described in https://github.com/karmann-dm/gradle-versions-plugin/issues/7
