### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Szer** [karmann-dm/gradle-versions-plugin#4]
Which licensing mechanism this project follows?

I want to fork it and tune for my private project needs.

Those needs probably won't be merged upstream (it relies around versioning multiple artifacts produced by Kotlin Multiplatform)

**Comment by karmann-dm** [comment]
Yes, sure.
https://github.com/karmann-dm/gradle-versions-plugin/commit/e413c9cbd309f5ce3693ef0876aa0dde0b1bc64c
